#+TITLE: Octocurious
#+OPTIONS: toc:nil

Greetings, Internet! I'm Christina O'Donnell, a computer science tutor and
enthusiast based in Cambridge, England.

You can find more information about my tutoring on [[https://octocurious.com/pages/tutoring.html][my tutoring services page]].

I have a First Class BA in Mathematics and Computer Science for University of
Oxford. You can read more about my professional history by downloading [[https://octocurious.com/include/files/cv.pdf][my CV]].

My research interest is a formal system I call SGL, that represents all concepts
as labeled directed graphs. Node identity is determined entirely by its outward
links (up to isomorphism). My ultimate aim is to create a common abstract
language that could allow programs, proofs and data to exist in the same 'space'.

Some of my projects can be found on [[https://github.com/cdo256][GitHub]].

I also play wheelchair basketball for [[http://www.heatwbc.org.uk/][Hareward Heat WBC]].

I am always happy to be contacted by all humans (as well as some high-quality
marketing bots!) For that, you can email me on [[mailto:christina@octocurious.com][christina@octocurious.com]] (or
equivalently [[mailto:cdo@mutix.org][cdo@mutix.org]]).

** Recent blog posts
#+INCLUDE: blog/index.org

See the [[https://octocurious.com/pages/blog.html][the full list of blog posts]].
