#+TITLE: Octocurious
#+OPTIONS: toc:nil

Greetings, Internet! I'm Christina O'Donnell, a computer science tutor and
enthusiast based in Cambridge, England.

You can find more information about my tutoring [[https://octocurious.com/pages/tutoring.html][here]].

I have a First Class BA in Mathematics and Computer Science for University of
Oxford.
# You can find my resume [[https://octocurious.com/pages/resume.html][here]]. -- TODO

My research interest is a mathematical structure I call 'semantic graphs' which
can be used to make an elegant pattern calculus of these semantic graphs. It's
all too early to publish yet, but publishing is the goal.

I also play wheelchair basketball for [[http://www.heatwbc.org.uk/][Hareward Heat WBC]].

Some of my projects can be found on [[https://github.com/cdo256][GitHub]].

I am always happy to be contacted by all humans (as well as some high-quality marketing
bots!) For that, you can email me on [[mailto:christina@octocurious.com][christina@octocurious.com]] (or equivalently [[mailto:cdo@mutix.org][cdo@mutix.org]]).

** Recent blog posts
#+INCLUDE: blog/index.org

The full list of blog posts is accessible [[https://octocurious.com/pages/blog.html][here]].
